# Generated by Django 3.0.5 on 2020-04-11 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('time_1', models.CharField(max_length=200, null=True)),
                ('time_2', models.CharField(max_length=200, null=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='blog_posts', serialize=False, to='home.Device')),
                ('time_3', models.CharField(max_length=200, null=True)),
                ('time_4', models.CharField(max_length=200, null=True)),
                ('time_5', models.CharField(max_length=200, null=True)),
                ('time_6', models.CharField(max_length=200, null=True)),
                ('time_7', models.CharField(max_length=200, null=True)),
                ('time_8', models.CharField(max_length=200, null=True)),
                ('time_9', models.CharField(max_length=200, null=True)),
                ('time_10', models.CharField(max_length=200, null=True)),
                ('setupcompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
