# Generated by Django 3.0.5 on 2020-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200411_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='time_10',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
