# Generated by Django 3.0.5 on 2020-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200412_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='time_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='time_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='time_4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='time_5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='time_6',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='time_7',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='time_8',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='time_9',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
