# Generated by Django 3.0.5 on 2020-04-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='min_moisture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='time_period',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
