# Generated by Django 3.0.5 on 2020-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='last_measured_moisture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='gpio',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='zone',
            name='last_active_moisture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='last_measured_moisture',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
