# Generated by Django 3.0.5 on 2020-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200413_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
