# Generated by Django 3.0.5 on 2020-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_zone_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connected',
            field=models.BooleanField(default=True),
        ),
    ]
